### ISSUE TITLE
mapotf-precommit.sh issue

### ISSUE THREAD

**Issue by msl0** [Azure/tfmod-scaffold#101]
Hey,
I have a problem with `./avm pre-commit` command on Linux in the avm-res-storage-storageaccount module.
This is a link to a failed Github workflow run https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/actions/runs/14840523026/job/41873012472?pr=241
I'm getting this error locally:
```
===> Generating documentation in ./private-endpoint-unmanage_dns_zone_group
private-endpoint-unmanage_dns_zone_group/README.md updated successfully
===> Generating documentation in ./management-policy
management-policy/README.md updated successfully
===> Generating documentation in ./data_lake_gen2
data_lake_gen2/README.md updated successfully
==> Generating sub modules documentation...
curl -H 'Cache-Control: no-cache, no-store' -sSL "https://raw.githubusercontent.com/Azure/tfmod-scaffold/main/avm_scripts/mapotf-precommit.sh" | bash
Error: parse "https://github.com:Azure/tfmod-scaffold.git": invalid port ":Azure" after host
make: *** [avmmakefile:100: mapotf-precommit] Error 1
```
Should `:` be replaced with `/`?

@lonegunmanb could you please check?

**Comment by lonegunmanb** [comment]
@msl0 thanks for reporting this issue to us, I believe it has been fixed by #103 , could you please give it a try? Thanks!

**Comment by lonegunmanb** [comment]
> When I run this command `curl -H 'Cache-Control: no-cache, no-store' -sSL "https://raw.githubusercontent.com/Azure/tfmod-scaffold/main/avm_scripts/mapotf-precommit.sh" | sed 's/:Azure/\/Azure/g' | bash` it updated main.telemetry.tf file
> 
> ```
> curl -H 'Cache-Control: no-cache, no-store' -sSL "https://raw.githubusercontent.com/Azure/tfmod-scaffold/main/avm_scripts/mapotf-precommit.sh" | sed 's/:Azure/\/Azure/g' | bash
> transform.update_in_place.telemetry_with_var_dot_location[telemetry] would be apply:
>  {"id":"da9c80f5-94e2-4a52-9914-bf21625988f1","patch":"patch{\ntags=merge({\n    subscription_id = one(data.azurerm_client_config.telemetry).subscription_id\n    tenant_id       = one(data.azurerm_client_config.telemetry).tenant_id\n    module_source   = one(data.modtm_module_source.telemetry).module_source\n    module_version  = one(data.modtm_module_source.telemetry).module_version\n    random_id       = one(random_uuid.telemetry).result\n  }, { location = var.location })\n}\n","target_block_address":"resource.modtm_telemetry.telemetry"}
> 
> ---
> 
> Transforms applied successfully.
> All backups have been cleaned.
> ```
> 
> It finished successfully, but I'm not familiar with this process

Yeah this is as expected, we have added a code transformation process in `pre-commit`, now it would update telemetry resource, adding module location into it. @msl0

**Comment by msl0** [comment]
@lonegunmanb it's working now!

**Comment by msl0** [comment]
I think I announced success too soon. I'm not sure if it works completely. Now I'm able to run `./avm pre-commit` locally and I did it, but when I updated my PR, the workflow is still failing. The workflow still says to run `./avm pre-commit`
https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/actions/runs/14923644067/job/41923806743?pr=241#step:3:165

**Comment by lonegunmanb** [comment]
@msl0 sorry for this one, I've checked the failed action log:

```text
AVMfix changes detected, please run:
> docker run --rm -v /home/runner/work/terraform-azurerm-avm-res-storage-storageaccount/terraform-azurerm-avm-res-storage-storageaccount:/src -w /src mcr.microsoft.com/azterraform make pre-commit
```

In the latest container I've bumped `avmfix` so it would sort arguments for `module` block now, would you please rerun `./avm pre-commit` or `./avm.bat pre-commit` on your machine and push the changes to remote if there's any? Thanks!

**Comment by msl0** [comment]
It worked for me after re-creating the codespace
