### ISSUE TITLE
Script Error in docs-gen.sh

### ISSUE THREAD

**Issue by terrymandin** [Azure/tfmod-scaffold#19]
There is a script error in [docs-gen.sh](https://github.com/Azure/tfmod-scaffold/blob/main/avm_scripts/docs-gen.sh).  It needs to cd back to the root directory on line 17.  I'm getting the following error:

```
C:\gitdesk\terraform-azurerm-avm-res-compute-virtualmachinescaleset>wsl
tmandin@DESKTOP-G4JRH9D:/mnt/c/gitdesk/terraform-azurerm-avm-res-compute-virtualmachinescaleset$ make docs
curl -H 'Cache-Control: no-cache, no-store' -sSL ""https://raw.githubusercontent.com/Azure/tfmod-scaffold/main/avm_scripts"/docs-gen.sh" | sh -s
==> Generating module documentation...
README.md updated successfully
==> Generating examples documentation...
===> Generating examples documentation in  ./examples/advanced
README.md updated successfully
===> Generating examples documentation in  ./examples/certificates
sh: 10: cd: can't cd to ./examples/certificates
README.md updated successfully
===> Generating examples documentation in  ./examples/default
sh: 10: cd: can't cd to ./examples/default
README.md updated successfully
===> Generating examples documentation in  ./examples/rbac-and-managed-identities
sh: 10: cd: can't cd to ./examples/rbac-and-managed-identities
README.md updated successfully
===> Generating examples documentation in  ./examples/windows
sh: 10: cd: can't cd to ./examples/windows
README.md updated successfully
```

Adding "cd ../.." on line 17 should fix it.  e.g.:

```
#!/usr/bin/env bash

echo "==> Generating module documentation..."
rm -f .terraform.lock.hcl
terraform-docs -c .terraform-docs.yml .
echo "==> Generating examples documentation..."
examples=$(find ./examples -maxdepth 1 -mindepth 1 -type d)
for d in $examples; do
  echo "===> Generating examples documentation in " $d
  cd $d
  rm -f .terraform.lock.hcl
  if [ -f "../.terraform-docs.yml" ]; then
  	terraform-docs -c ../.terraform-docs.yml .
  else
  	terraform-docs markdown table --output-file README.md --output-mode inject .
  fi
  cd ../..
done
```

**Comment by terrymandin** [comment]
@lonegunmanb

**Comment by terrymandin** [comment]
@kewalaka, why not make it work for all examples.  Seems like a simple fix?

**Comment by prjelesi** [comment]
@matt-FFFFFF

**Comment by matt-FFFFFF** [comment]
Yeah good catch will fix

**Comment by matt-FFFFFF** [comment]
We can use the path to module parameter and avoid all the `cd` commands

**Comment by matt-FFFFFF** [comment]
This is fixed now

**Comment by terrymandin** [comment]
There still seems to be an error in the script.  It appears to be appending the directory name twice in the path.  See below:
<img width="825" alt="image" src="https://github.com/Azure/tfmod-scaffold/assets/833055/27832d6c-08f1-4b34-a9ff-310764e4c4ca">
@matt-FFFFFF @lonegunmanb

**Comment by matt-FFFFFF** [comment]
Strange, works here. Will investigate

```text
❯ make docs
curl -H 'Cache-Control: no-cache, no-store' -sSL ""https://raw.githubusercontent.com/Azure/tfmod-scaffold/main/avm_scripts"/docs-gen.sh" | sh -s
==> Generating module documentation...
README.md updated successfully
==> Generating examples documentation...
===> Generating examples documentation in ./diagnostic-settings
diagnostic-settings/README.md updated successfully
===> Generating examples documentation in ./default
default/README.md updated successfully
===> Generating examples documentation in ./private-endpoint
private-endpoint/README.md updated successfully
```

**Comment by matt-FFFFFF** [comment]
I see the issue!

You can fix this by creating the `examples/.terraform-docs.yml`

But... there is also an error in the script here:

https://github.com/Azure/tfmod-scaffold/blob/06d9676fb816e63ab0cc20e340d1adf9c7ff01c8/avm_scripts/docs-gen.sh#L10

**Comment by matt-FFFFFF** [comment]
Hopefully now fixed:

https://github.com/Azure/tfmod-scaffold/blob/9dcc838442efb2dbc9604d6566cf8044769812df/avm_scripts/docs-gen.sh#L10

**Comment by terrymandin** [comment]
That worked, thank you!!
<img width="725" alt="image" src="https://github.com/Azure/tfmod-scaffold/assets/833055/e814fe57-f01f-48d0-8a83-02d8d6ff6f1d">

**Comment by terrymandin** [comment]
I am seeing a different issue now.  Is this related or should I create a new issue?  It happens on my desktop too.

<img width="345" alt="image" src="https://github.com/Azure/tfmod-scaffold/assets/833055/3794b904-c215-4196-a643-ed3f4149f990">

@matt-FFFFFF

**Comment by kewalaka** [comment]
hi @terrymandin - I think your docs-check github action might be out of date, you could try with the copy here;

https://github.com/Azure/terraform-azurerm-avm-template/blob/main/.github/actions/docs-check/action.yml

this relies on the new container image which is part of the governance checks being introduced.  if that doesn't work, the previous way to do it can be borrowed from here.

https://github.com/Azure/terraform-azurerm-avm-res-containerregistry-registry/blob/main/.github/actions/docs-check/action.yml
(but please only use this as a last resort)

**Comment by matt-FFFFFF** [comment]
Apologies @terrymandin this was a regression - I have re-added make tools target for now

**Comment by terrymandin** [comment]
Thanks @matt-FFFFFF .  Turns out my github actions were also out of date.  I updated them and am now seeing this error in my build.  Seems to be related to the avmfix tool.

<img width="853" alt="image" src="https://github.com/Azure/tfmod-scaffold/assets/833055/4f58e315-6b12-4520-bd5c-627263301cc6">

**Comment by matt-FFFFFF** [comment]
Please can you revert to the old e2e yml file? This should fix the issue.

I apologise for all the disruption we have with the testing at the moment. We are very close to rolling out the new approach and things will get easier.

**Comment by terrymandin** [comment]
Will do, which version should I use?

<img width="916" alt="image" src="https://github.com/Azure/tfmod-scaffold/assets/833055/c02f78d2-440a-4e11-a059-e9e0c5ef67a4">

**Comment by terrymandin** [comment]
Never mind, I copied the VM AVM e2e.yml.  That worked.

**Comment by terrymandin** [comment]
@matt-FFFFFF, I spoke too soon.  Even with the VM AVM e2e.yml file I am still getting the ```go.mod:3: invalid go version '1.21.2': must match format 1.23``` error.  

Should I just wait until the new approach is out?  If so, can you give me an e.t.a.?

**Comment by kewalaka** [comment]
@terrymandin I've got a working pipeline that satisfies the governance tests for currently available functionality on this PR branch here:

https://github.com/kewalaka/terraform-azurerm-avm-res-containerregistry-registry/tree/feat/add-webhook-support

Suggest replacing the entire .github folder & makefile.

otherwise - if you share your current repo with me I'm happy to have a quick look.

**Comment by terrymandin** [comment]
I was able to get it working with @kewalaka 's .github files.
